### ISSUE TITLE
Color theme

### ISSUE THREAD

**Issue by kermitt2** [anHALytics/anHALytics-frontend#21]
Normally we should avoid mixing cold and warm color, e.g. put blue stuff in the warm colors. The initial front-end was following "analogous colors" theme (with only warm colors) - I always pay attention to that in my demos. 

![screen shot 2016-07-04 at 21 27 50](https://cloud.githubusercontent.com/assets/2340795/16568769/4634ade8-422e-11e6-814d-3af3f52b2c3b.png)

![screen shot 2016-07-04 at 21 28 20](https://cloud.githubusercontent.com/assets/2340795/16568770/4a78e95a-422e-11e6-989e-82c85d643174.png)

There are a lot on the web on color theory, e.g. http://www.tigercolor.com/color-lab/color-theory/color-theory-intro.htm

**Comment by Aazhar** [comment]
fixed since 0f4de25
