### ISSUE TITLE
Abstract and metadata pre-loaded in background

### ISSUE THREAD

**Issue by kermitt2** [anHALytics/anHALytics-frontend#22]
In the initial frontend the annotated abstract and the metadata for an article were uploaded in background for a search result page. The abstract could then be view immediately with all metadata when clicking on the entry. 

In the new front-end, there is a "white" flash when the asbtract or the metadata are clicked, with a resizing.

**Comment by Aazhar** [comment]
the loading behaviour was not changed actually this is due to using collapsible panel, it will be resolved with #23
