### ISSUE TITLE
Alignment of search in front page

### ISSUE THREAD

**Issue by lfoppiano** [anHALytics/anHALytics-frontend#32]
When you open the search page, the text and the searchbox don't seems well aligned. 

<img width="1330" alt="screen shot 2016-07-11 at 09 37 07 copy" src="https://cloud.githubusercontent.com/assets/15426/16723302/6e90bb6a-474c-11e6-81a0-3ba2db9c3c88.png">

Even selecting different values in the drop-down boxes the page remaind disaligned.

**Comment by kermitt2** [comment]
I would put the search bar then exactly at the same position as in the result page then (at the top). At the same time I am not sure about the added value of this front page, we could think in the future about something more informative (with widgets and updates, ..) when aggregated views will be available.

**Comment by atlasian** [comment]
@kermitt2 The added value of this page is to get a general idea and documentation of the project, it's not yet complete, I need to update the readme and github doc first to finish it.

**Comment by Aazhar** [comment]
@kermitt2 The added value of this page is to get a general idea and documentation of the project(especially for people who are new), it's not yet complete, I need to update the readme and github doc first to finish it.

**Comment by lfoppiano** [comment]
@Aazhar it might be worth do a test with them swapped. The search box on top and the description in the middle.

**Comment by atlasian** [comment]
I think , It looks better
![image](https://cloud.githubusercontent.com/assets/1577714/17178382/9fbb95a4-5415-11e6-8450-3a6ba40c2a07.png)

**Comment by lfoppiano** [comment]
Indeed. I think having the text "Anhalytics is a project [...]" is nice the first three times you read it... If you use it a lot (imagine how you use google). It's nicer to have a minimalist search form. 

IMHO You could have a specific page with all information about what AnHALytics is more in details.

**Comment by Aazhar** [comment]
actually I've built a wordpress website here : https://project.inria.fr/anhalytics/ and there is also a github repository https://github.com/anHALytics/documentation which I'm preparing to build a readthedocs(https://readthedocs.org) to have something like what Patrice have made for Grobid..

**Comment by Aazhar** [comment]
@lfoppiano you mean search all fields by default ?

**Comment by lfoppiano** [comment]
I meant to have only the search form to start with. ;-)

**Comment by Aazhar** [comment]
ah ok so you agree with the idea of kermitt2

**Comment by lfoppiano** [comment]
lol, somehow yes, I've said more or less the same thing :D
