### ISSUE TITLE
[minor] multiple search criteria cannot be removed from the interface

### ISSUE THREAD

**Issue by lfoppiano** [anHALytics/anHALytics-frontend#35]
As you can see in the picture below, there is no way search criteria can be removed. 
<img width="1299" alt="screen shot 2016-07-12 at 09 24 37" src="https://cloud.githubusercontent.com/assets/15426/16758652/2e1c4b7c-4813-11e6-85c5-7b1d217e6c95.png">

Also they are shown in the result page. 
<img width="1226" alt="screen shot 2016-07-12 at 09 28 09" src="https://cloud.githubusercontent.com/assets/15426/16758640/20335f28-4813-11e6-9b26-c77f2bf5df3a.png">

I think this is a minor issue, but I'm not sure it's really an issue itself.

**Comment by kermitt2** [comment]
This is not a minor usability issues, rather an important one imho. 

Suggestion ->
- removing  the button "+ add new search field" (it takes a whole line and create empty space)
- add a button with just "+" on the right of the search bar
- when a second or more search bar are added, add a button "-" in addition on the right of the search bar to remove the field

So, the behaviour would be similar to the "Advanced search" of HAL, see https://hal.archives-ouvertes.fr/search/index - which I find really good!

**Comment by Aazhar** [comment]
Fixed in 942c038

**Comment by kermitt2** [comment]
For this one I still think the current button "+ add new search field" is too large and create useless empty space and we should use simple and clear "+" and "-" buttons as suggested above !

**Comment by kermitt2** [comment]
Just need some cleaning in the positions... I am doing it.

**Comment by kermitt2** [comment]
8082b67ceddee0bcceae8c983105c3be395bcce0
ok still 1 issue and 1 thing to do
- issue: the + and - glyphicons are not centered in the button
- todo: call a dosearch() when removing a field if the corresponding freetext field is not empty
