### ISSUE TITLE
recherche sur organisation 

### ISSUE THREAD

**Issue by Jaigu** [anHALytics/anHALytics-frontend#48]
bizarrerie 
je vais sur http://traces2.saclay.inria.fr/inria_demo/organisation_dashboard.html?orgID=5
dans "Organisation relations", je choisis Inria Rennes Bretagne Atlantique (d'ailleurs, ce serait bien si on pouvait voir l'intégralité des libellés des centres Inria)
voir capture1
![capture1](https://cloud.githubusercontent.com/assets/16720895/20517131/0b42d1f8-b09a-11e6-96f5-e60b943f48c5.PNG)
mon url reste http://traces2.saclay.inria.fr/inria_demo/organisation_dashboard.html?orgID=5 : je m'attendais à avoir un l' ID de Inria Rennes Bretagne Atlantique
je choisis "METISS"
![capture2](https://cloud.githubusercontent.com/assets/16720895/20517167/26e23d7c-b09a-11e6-8853-43046df86ab8.PNG)
et là, je n'ai plus aucun résultat 
![capture3](https://cloud.githubusercontent.com/assets/16720895/20517185/40cd7940-b09a-11e6-9def-ea9dab99feea.PNG) 
et si je fais un back dans mon navigateur, j'arrive sur http://traces2.saclay.inria.fr/inria_demo/organisation_dashboard.html?orgID=8 (INPG)
merci
à+
Anne

**Comment by Aazhar** [comment]
Je viens de corriger la redirection, pour ce qui est des résultats pour Metiss il s'agit d'une équipe qui n'a pas donc de sous structures
