### ISSUE TITLE
Publications per year

### ISSUE THREAD

**Issue by Jaigu** [anHALytics/anHALytics-frontend#49]
re-bonjour,
http://traces2.saclay.inria.fr/inria_demo/organisation_dashboard.html?orgID=5
l'affichage des publications par année est illisible et aucun chiffre dans l'ordonnée
![capture4](https://cloud.githubusercontent.com/assets/16720895/20517621/3b2322e0-b09c-11e6-8e4f-12b8d4bb24b7.PNG)
j'aurais bien aimé pouvoir visualiser une année
merci
à+
Anne

**Comment by Aazhar** [comment]
Ok c'est corrigé maintenant , ça ressemble à ça:
![image](https://cloud.githubusercontent.com/assets/9571357/20672658/5764ddfa-b582-11e6-8684-129a7ee9cb92.png)

**Comment by Jaigu** [comment]
Achraf,
ce serait bien d'avoir les données au moins jusque 2017
![capture](https://cloud.githubusercontent.com/assets/16720895/20705344/da9321aa-b622-11e6-94fa-a5f2fb6fccdc.PNG)
merci
Anne
