### ISSUE TITLE
Keyterm "Apport" on Inria dashboard

### ISSUE THREAD

**Issue by kermitt2** [anHALytics/anHALytics-frontend#77]
What the hell is this keyterm "Apport" so high in the old Inria publications? @kermitt2, check quality !

![screenshot from 2016-12-22 17-07-18](https://cloud.githubusercontent.com/assets/2340795/21432284/0dd4b9d4-c86b-11e6-8d2e-2b835083e43e.png)

**Comment by Aazhar** [comment]
this is because in hal the majority of reports are deposited by an editor named 'Rapport de recherche' : https://hal.archives-ouvertes.fr/inria-00069991/tei

it should be ok with : https://github.com/kermitt2/grobid-keyterm/commit/78fd02f5d45a533662d31a95ffcf35131e2f98ad

**Comment by kermitt2** [comment]
Added the correction to start tag too. 
https://github.com/kermitt2/grobid-keyterm/commit/e8bfe632c0b947c66d9b5bf110cf07654ebc3383
